buildlimit: 10
instlimit: -1
memlimit: 512
path:
  compiler: /mnt/c/Users/runzhe/IdeaProjects/Compiler/judge
  dataset: /mnt/c/Users/runzhe/IdeaProjects/Compiler/judge/testcase
  simulator: /mnt/c/Users/runzhe/IdeaProjects/Compiler/judge
  simulator-executable: ravel
  built-in: /mnt/c/Users/runzhe/IdeaProjects/Compiler/builtin.s
# stage: semantic
stage: codegen
timelimit: 100